// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qBeqAySY6XtGP7qTvUwvYSWqDGOUcOw',
    appId: '1:366924226852:android:3b9c65e5be0cc9b26d13b1',
    messagingSenderId: '366924226852',
    projectId: 'menu-minder-f9262',
    storageBucket: 'menu-minder-f9262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIgKJMcwDlA6y94Ulc9RFqq9Rx8KkCInc',
    appId: '1:366924226852:ios:fd7858c1c27f44056d13b1',
    messagingSenderId: '366924226852',
    projectId: 'menu-minder-f9262',
    storageBucket: 'menu-minder-f9262.firebasestorage.app',
    androidClientId: '366924226852-1ahcv1gupg0lnehuth0peugcpr4jrd49.apps.googleusercontent.com',
    iosClientId: '366924226852-utuvdocc0ks1mrkbovtff3bq1c63ojrh.apps.googleusercontent.com',
    iosBundleId: 'com.appsnado.menuminder',
  );

}