///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateProfileModel {
/*
{
  "user_image": "",
  "user_name": "",
  "user_phone": "",
  "address": "",
  "state": "",
  "city": "",
  "country": "",
  "long": "",
  "lat": "",
  "food_peferences": [
    ""
  ],
  "diet_peferences": [
    ""
  ]
} 
*/

  String? userImage;
  String? userName;
  String? userPhone;
  String? address;
  String? state;
  String? userCountryCode;
  String? email;
  String? city;
  String? country;
  String? alternateEmail;
  String? long;
  String? refrealCode;
  String? lat;
  List<String?>? breakFastPrefrences;
  List<String?>? lunchPrefrences;
  List<String?>? dinnerPrefrences;
  List<String?>? dietPeferences;

  CreateProfileModel({
    this.userImage,
    this.userName,
    this.userPhone,
    this.address,
    this.state,
    this.userCountryCode,
    this.email,
    this.city,
    this.refrealCode,
    this.country,
    this.alternateEmail,
    this.long,
    this.lat,
    this.breakFastPrefrences,
    this.lunchPrefrences,
    this.dinnerPrefrences,
    this.dietPeferences,
  });
  CreateProfileModel.fromJson(Map<String, dynamic> json) {
    userImage = json['user_image']?.toString();
    userName = json['user_name']?.toString();
    userPhone = json['user_phone']?.toString();
    email = json['user_email']?.toString();
    alternateEmail = json['user_alternative_email'];
    address = json['address']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    country = json['country']?.toString();
    userCountryCode = json['user_country_code']?.toString();
    long = json['long']?.toString();
    lat = json['lat']?.toString();
    if (json['breakfast_peferences'] != null) {
      final v = json['breakfast_peferences'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      breakFastPrefrences = arr0;
    }

    if (json['lunch_peferences'] != null) {
      final v = json['lunch_peferences'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      lunchPrefrences = arr0;
    }

    if (json['dinner_peferences'] != null) {
      final v = json['dinner_peferences'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      dinnerPrefrences = arr0;
    }

    if (json['diet_peferences'] != null) {
      final v = json['diet_peferences'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      dietPeferences = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_image'] = userImage;
    data['user_name'] = userName;
    data['user_phone'] = userPhone;
    data['address'] = address;
    data['state'] = state;
    data['city'] = city;
    data['user_alternative_email'] = alternateEmail;
    data['user_email'] = email;
    data['country'] = country;
    data['user_country_code'] = userCountryCode;
    data['long'] = long;
    data['refCode'] = refrealCode;
    data['lat'] = lat;
    if (breakFastPrefrences != null) {
      final v = breakFastPrefrences;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['breakfast_peferences'] = arr0;
    }

    if (lunchPrefrences != null) {
      final v = lunchPrefrences;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['lunch_peferences'] = arr0;
    }

    if (dinnerPrefrences != null) {
      final v = dinnerPrefrences;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['dinner_peferences'] = arr0;
    }

    if (dietPeferences != null) {
      final v = dietPeferences;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['diet_peferences'] = arr0;
    }
    return data;
  }
}
