///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModel {
/*
{
  "email": "hashim2@gmail.com",
  "password": "Abcd@1234",
  "device_token": "adasdfsfsdf",
  "device_type": "ios",
  "role": "user"
} 
*/

  String? email;
  String? device_token;
  String? device_type;

  LoginModel({
    this.email,
    this.device_token,
    this.device_type,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    email = json['user_email']?.toString();
    device_token = json['device_token']?.toString();
    device_type = json['device_type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_email'] = email;
    data['user_device_token'] = device_token;
    data['user_device_type'] = device_type;

    return data;
  }
}
