///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OtpVerificationModel {
/*
{
  "user_id": "1",
  "user_verification_code": "123456",
  "type": "forgot"
} 
*/

  String? userId;
  String? verifiedCode;

  OtpVerificationModel({
    this.userId,
    this.verifiedCode,
  });
  OtpVerificationModel.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
    verifiedCode = json['user_verification_code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['user_verification_code'] = verifiedCode;
    return data;
  }
}
