///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResendOTPCodeModel {
/*
{
  "email": "Hasmhmi",
  "otp_type": "DuwaKhana"
} 
*/

  String? user_id;

  ResendOTPCodeModel({
    this.user_id,
  });
  ResendOTPCodeModel.fromJson(Map<String, dynamic> json) {
    user_id = json['user_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = user_id;
    return data;
  }
}
