///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SocialQueryModel {
/*
{
  "access_token": "12454545457454754",
  "provider": "google",
  "device_type": "android",
  "device_token": "123",
  "name": "social user",
  "email": "social_user@getnada.com"
} 
*/

  String? userSocialtoken;
  String? userSocialType;
  String? userDeviceType;
  String? userDeviceToken;
  String? countryCode;
  String? name;

  String? userEmail;
  String? userPhone;

  SocialQueryModel({
    this.userSocialtoken,
    this.userSocialType,
    this.countryCode,
    this.userDeviceType,
    this.userDeviceToken,
    this.userEmail,
    this.userPhone,
    this.name,
  });
  SocialQueryModel.fromJson(Map<String, dynamic> json) {
    userSocialtoken = json['user_social_token']?.toString();
    userSocialType = json['user_social_type']?.toString();
    userDeviceType = json['user_device_type']?.toString();
    userDeviceToken = json['user_device_token']?.toString();
    countryCode = json['user_country_code']?.toString();
    userEmail = json['user_email']?.toString();
    userPhone = json['user_phone']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_social_token'] = userSocialtoken;
    data['user_social_type'] = userSocialType;
    data['user_device_type'] = userDeviceType;
    data['user_device_token'] = userDeviceToken;
    data['user_country_code'] = countryCode;
    data['user_email'] = userEmail;
    data['user_phone'] = userPhone;
    data['name'] = name;
    return data;
  }
}
