///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModelDataUserLocation {
/*
{
  "address": "null",
  "state": "null",
  "city": "null",
  "country": "null",
  "type": "Point",
  "coordinates": [
    0
  ]
} 
*/

  String? address;
  String? state;
  String? city;
  String? country;
  String? type;
  List<int?>? coordinates;

  UserModelDataUserLocation({
    this.address,
    this.state,
    this.city,
    this.country,
    this.type,
    this.coordinates,
  });
  UserModelDataUserLocation.fromJson(Map<String, dynamic> json) {
    address = json['address']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    country = json['country']?.toString();
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['address'] = address;
    data['state'] = state;
    data['city'] = city;
    data['country'] = country;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class UserModelData {
/*
{
  "user_location": {
    "address": "null",
    "state": "null",
    "city": "null",
    "country": "null",
    "type": "Point",
    "coordinates": [
      0
    ]
  },
  "user_device_type": "null",
  "user_device_token": "null",
  "_id": "6560a573f61ab5b1dc91d922",
  "user_image": "uploads\\profile\\2023-11-24T13-28-35.927ZWtW-01.png",
  "user_name": "AV",
  "user_email": "test2@getnada.com",
  "user_phone": "null",
  "food_peferences": [
    "W"
  ],
  "diet_peferences": [
    "dfs"
  ],
  "user_role": "User",
  "user_verification_code": "null",
  "user_is_verified": 1,
  "user_is_notification": 1,
  "user_is_blocked": 0,
  "user_is_delete": 0,
  "user_is_complete": 1,
  "user_authentication": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoidGVzdDJAZ2V0bmFkYS5jb20iLCJ1c2VyX2lkIjoiNjU2MGE1NzNmNjFhYjViMWRjOTFkOTIyIiwiaWF0IjoxNzAxNjkwNTg2fQ.fx8xjlt4GdXLoeEGt013OUSIii2n1rXBeGf7w2hf170",
  "user_social_token": "null",
  "user_social_type": "null",
  "createdAt": "2023-11-24T13:30:27.105Z",
  "updatedAt": "2023-12-04T11:49:46.636Z",
  "__v": 0
} 
*/

  UserModelDataUserLocation? userLocation;
  String? userDeviceType;
  String? userDeviceToken;
  String? Id;
  String? userImage;
  String? userName;
  String? userEmail;
  int? userIsSubscribed;
  String? userPhone;
  String? userCountryCode;
  List<String?>? foodPeferences;
  List<String?>? dietPeferences;
  String? userRole;
  String? userVerificationCode;
  int? userIsVerified;
  int? userIsNotification;
  int? userIsBlocked;
  int? userIsDelete;
  int? userIsComplete;
  String? userAuthentication;
  String? userSocialToken;
  String? userSocialType;
  String? createdAt;
  String? userAlternateEmail;
  String? updatedAt;
  int? _V;

  UserModelData({
    this.userLocation,
    this.userDeviceType,
    this.userDeviceToken,
    this.Id,
    this.userImage,
    this.userName,
    this.userEmail,
    this.userIsSubscribed,
    this.userPhone,
    this.foodPeferences,
    this.dietPeferences,
    this.userCountryCode,
    this.userRole,
    this.userVerificationCode,
    this.userIsVerified,
    this.userAlternateEmail,
    this.userIsNotification,
    this.userIsBlocked,
    this.userIsDelete,
    this.userIsComplete,
    this.userAuthentication,
    this.userSocialToken,
    this.userSocialType,
    this.createdAt,
    this.updatedAt,
  });
  UserModelData.fromJson(Map<String, dynamic> json) {
    userLocation = (json['user_location'] != null)
        ? UserModelDataUserLocation.fromJson(json['user_location'])
        : null;
    userDeviceType = json['user_device_type']?.toString();
    userDeviceToken = json['user_device_token']?.toString();
    Id = json['_id']?.toString();
    userImage = json['user_image']?.toString();
    userName = json['user_name']?.toString();
    userEmail = json['user_email']?.toString();
    userPhone = json['user_phone']?.toString();
    userAlternateEmail = json['user_alternative_email'];
    userIsSubscribed = json['user_is_subscribed'];
    userCountryCode = json['user_country_code'];
    if (json['food_peferences'] != null) {
      final v = json['food_peferences'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      foodPeferences = arr0;
    }
    if (json['diet_peferences'] != null) {
      final v = json['diet_peferences'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      dietPeferences = arr0;
    }
    userRole = json['user_role']?.toString();
    userVerificationCode = json['user_verification_code']?.toString();
    userIsVerified = json['user_is_verified']?.toInt();
    userIsNotification = json['user_is_notification']?.toInt();
    userIsBlocked = json['user_is_blocked']?.toInt();

    userIsDelete = json['user_is_delete']?.toInt();
    userIsComplete = json['user_is_complete']?.toInt();
    userAuthentication = json['user_authentication']?.toString();
    userSocialToken = json['user_social_token']?.toString();
    userSocialType = json['user_social_type']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    _V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (userLocation != null) {
      data['user_location'] = userLocation!.toJson();
    }
    data['user_device_type'] = userDeviceType;
    data['user_device_token'] = userDeviceToken;
    data['_id'] = Id;
    data['user_image'] = userImage;
    data['user_name'] = userName;
    data['user_email'] = userEmail;
    data['user_phone'] = userPhone;
    data['user_alternative_email'] = userAlternateEmail;
    data['user_country_code'] = userCountryCode;
    if (foodPeferences != null) {
      final v = foodPeferences;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['food_peferences'] = arr0;
    }
    if (dietPeferences != null) {
      final v = dietPeferences;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['diet_peferences'] = arr0;
    }
    data['user_role'] = userRole;
    data['user_verification_code'] = userVerificationCode;
    data['user_is_verified'] = userIsVerified;
    data['user_is_notification'] = userIsNotification;
    data['user_is_blocked'] = userIsBlocked;
    data['user_is_delete'] = userIsDelete;
    data['user_is_complete'] = userIsComplete;
    data['user_authentication'] = userAuthentication;
    data['user_social_token'] = userSocialToken;
    data['user_social_type'] = userSocialType;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = _V;
    return data;
  }
}

class UserModel {
/*
{
  "status": 1,
  "message": "OTP verified.",
  "data": {
    "user_location": {
      "address": "null",
      "state": "null",
      "city": "null",
      "country": "null",
      "type": "Point",
      "coordinates": [
        0
      ]
    },
    "user_device_type": "null",
    "user_device_token": "null",
    "_id": "6560a573f61ab5b1dc91d922",
    "user_image": "uploads\\profile\\2023-11-24T13-28-35.927ZWtW-01.png",
    "user_name": "AV",
    "user_email": "test2@getnada.com",
    "user_phone": "null",
    "food_peferences": [
      "W"
    ],
    "diet_peferences": [
      "dfs"
    ],
    "user_role": "User",
    "user_verification_code": "null",
    "user_is_verified": 1,
    "user_is_notification": 1,
    "user_is_blocked": 0,
    "user_is_delete": 0,
    "user_is_complete": 1,
    "user_authentication": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoidGVzdDJAZ2V0bmFkYS5jb20iLCJ1c2VyX2lkIjoiNjU2MGE1NzNmNjFhYjViMWRjOTFkOTIyIiwiaWF0IjoxNzAxNjkwNTg2fQ.fx8xjlt4GdXLoeEGt013OUSIii2n1rXBeGf7w2hf170",
    "user_social_token": "null",
    "user_social_type": "null",
    "createdAt": "2023-11-24T13:30:27.105Z",
    "updatedAt": "2023-12-04T11:49:46.636Z",
    "__v": 0
  }
} 
*/

  int? status;
  String? message;
  UserModelData? data;

  UserModel({
    this.status,
    this.message,
    this.data,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? UserModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
